name: JAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Java y Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Cambia si usas otra versi칩n

      - name: 游늭 Moverse al directorio correcto
        run: exercise # Aseg칰rate de poner el nombre correcto de la carpeta donde est치 `pom.xml`

      - name: 游댢 Compilar el proyecto con Maven
        run: mvn clean package
        working-directory: exercise/pom.xml  # Especifica el directorio donde est치 `pom.xml`

      - name: 游 Ejecutar el `.jar`
        run: java -jar target/*.jar
        working-directory: exercise/target/exercise-1.0.1-SNAPSHOT.jar  # Especifica el directorio donde est치 el `.jar`
